Nikki/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  post 'diaries/new', to: 'diaries#create'

  resources :users, only: %i[new create destroy]
  resources :diaries do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

Nikki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Nikki/app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :user_id, uniqueness: { scope: :diary_id }
end

Nikki/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :body, presence: true, length: { maximum: 60_000}
end

Nikki/app/models/diary.rb
class Diary < ApplicationRecord
  mount_uploader :diary_image, DiaryImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 60_000 }

end

Nikki/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_diaries, through: :bookmarks, source: :diary

  validates :password, length: { minimum: 6, maximum: 20 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true, length: { minimum: 3, maximum: 16 }

  def own?(object)
    id == object.user_id
  end

  def bookmark(diary)
    bookmark_diaries << diary
  end

  def unbookmark(diary)
    bookmark_diaries.destroy(diary)
  end

  def bookmark?(diary)
    bookmark_diaries.include?(diary)
  end
end

Nikki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  def logged_in?
    !current_user.nil?
  end

  private

  def not_authenticated
    flash[:warning] = t('default.message.require_login')
    redirect_to login_path
  end
end

Nikki/app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @diary = Diary.find(params[:diary_id])
    current_user.bookmark(@diary)
  end

  def destroy
    @diary = current_user.bookmarks.find(params[:id]).diary
    current_user.unbookmark(@diary)
  end
end

Nikki/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def index
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
    # respond_to do |format|
    #   format.html { redirect_to @user }
    #   format.js
    # end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    # respond_to do |format|
    #   format.html { redirect_to @user }
    #   format.js
    # end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(diary_id: params[:diary_id])
  end
end

Nikki/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @q = Diary.ransack(params[:q])
    @diaries =  @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
      @diary = Diary.new
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      redirect_to  new_diary_path, success: t('defaults.message.created', item: Diary.model_name.human)
    else
      redirect_to  new_diary_path, danger: t('defaults.message.not_created', item: Diary.model_name.human)
    end
  end

  def show
    @diary = Diary.find(params[:id])
    @comment = Comment.new
    @comments = @diary.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @diary = current_user.diaries.find(params[:id])
  end

  def update
    @diary = current_user.diaries.find(params[:id])
    if @diary.update(diary_params)
      redirect_to @diary, success: t('defaults.message.updated', item: Diary.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Diary.model_name.human)
      render :edit
    end
  end

  def destroy
    @diary = current_user.diaries.find(params[:id])
    @diary.destroy!
    redirect_to diaries_path, success: t('defaults.message.deleted', item: Diary.model_name.human)
  end

  def bookmarks
    @q = current_user.bookmark_diaries.ransack(params[:q])
    @bookmark_diaries = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :body, :diary_image, :diary_image_cache, :comments, :page)
  end
end

Nikki/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def show; end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :name, :avatar, :avatar_cache)
  end
end

Nikki/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]
end

Nikki/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to diaries_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def guest_login
    @guest_user = User.create(
      name: 'ゲストユーザー',
      email: SecureRandom.alphanumeric(10) + "@email.com",
      password: 'password',
      password_confirmation: 'password'
    )
    auto_login(@guest_user)
    redirect_to root_path, success: t('.success')
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

Nikki/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render:new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

Nikki/app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = '短冊日記'

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end
end

Nikki/app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

Nikki/app/helpers/comments_helper.rb
module CommentsHelper
end

Nikki/app/helpers/diaries_helper.rb
module DiariesHelper
end

Nikki/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

Nikki/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Nikki/app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    !current_user.nil?
  end
end

Nikki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if logged_in? %>
      <%= render 'layouts/shared/header' %>
    <% else %>
      <%= render 'layouts/shared/before_login_header' %>
    <% end %>
      <%= render 'layouts/shared/flash_message' %>
    <%= yield %>
      <%= render 'layouts/shared/footer' %>
  </body>
</html>

Nikki/app/views/layouts/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', size: '50x50' %>
    <% end %>

    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to (t'defaults.login'), login_path ,class: 'nav-link' %>
          <%= link_to (t'defaults.guest_login'), guest_login_path ,class: 'nav-link', method: :post %>
        </li>
      </ul>
    </div>
  </nav>
</header>

Nikki/app/views/layouts/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Nikki/app/views/layouts/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

Nikki/app/views/layouts/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Nikki © 2022. </p>
        </div>
      </div>
    </div>
  </div>
</footer>

Nikki/app/views/layouts/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', size: '50x50' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item active">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= Diary.model_name.human %>
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to t('diaries.index.title'), diaries_path, class: 'dropdown-item' %>
            <%= link_to t('diaries.new.title'), new_diary_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to  t('diaries.bookmarks.title'), bookmarks_diaries_path, class: 'nav-link' %>
          <%= link_to t('defaults.logout'), logout_path, class: 'dropdown-item', method: :delete %>
        </li>
        <li class="nav-item dropdown dropdown-slide">
            <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
              <%= image_tag current_user.avatar_url, size: '40x40', class: 'rounded-circle mr15'%>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-item"><%= current_user.decorate.user_name %></div>
              <div class="dropdown-divider"></div>
              <%= link_to (t 'profiles.show.title'), profile_path, class: 'dropdown-item' %>
              <%= link_to (t 'defaults.logout'), logout_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
      </ul>
    </div>
  </nav>
</header>