Nikki/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  post 'diaries/new', to: 'diaries#create'

  resources :users, only: %i[new create destroy]
  resources :diaries do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

Nikki/app/models/diary.rb
class Diary < ApplicationRecord
  mount_uploader :diary_image, DiaryImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 60_000 }

end

Nikki/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @q = Diary.ransack(params[:q])
    @diaries =  @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
      @diary = Diary.new
  end

  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      redirect_to  new_diary_path, success: t('defaults.message.created', item: Diary.model_name.human)
    else
      redirect_to  new_diary_path, danger: t('defaults.message.not_created', item: Diary.model_name.human)
    end
  end

  def show
    @diary = Diary.find(params[:id])
    @comment = Comment.new
    @comments = @diary.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @diary = current_user.diaries.find(params[:id])
  end

  def update
    @diary = current_user.diaries.find(params[:id])
    if @diary.update(diary_params)
      redirect_to @diary, success: t('defaults.message.updated', item: Diary.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Diary.model_name.human)
      render :edit
    end
  end

  def destroy
    @diary = current_user.diaries.find(params[:id])
    @diary.destroy!
    redirect_to diaries_path, success: t('defaults.message.deleted', item: Diary.model_name.human)
  end

  def bookmarks
    @q = current_user.bookmark_diaries.ransack(params[:q])
    @bookmark_diaries = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :body, :diary_image, :diary_image_cache, :comments, :page)
  end
end

Nikki/app/helpers/diaries_helper.rb
module DiariesHelper
end

Nikki/app/views/diaries/_bookmark.html.erb
<%= link_to bookmarks_path(diary_id: diary.id),
            id: "js-bookmark-button-for-diary-#{diary.id}", class:"float-right",
            method: :post,
            remote: true do %>
  <%= icon 'far', 'star' %>
<% end %>

Nikki/app/views/diaries/_bookmark_button.html.erb
<% if current_user.bookmark?(diary) %>
  <%= render 'unbookmark', { diary: diary } %>
<% else %>
  <%= render 'bookmark', { diary: diary } %>
<% end %>

Nikki/app/views/diaries/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_diary_path(diary), id: "button-edit-#{diary.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to diary_path(diary), id: "button-delete-#{diary.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

Nikki/app/views/diaries/_diary.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="diary-id-<%= diary.id %>">
    <div class="card">
    <%= image_tag diary.diary_image_url, class: 'card-img-top', size: '300x200' %>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to diary.title, diaries_path(diary)%>
        </h4>
        <% if current_user.own?(diary) %>
          <%= render 'crud_menus', diary: diary %>
        <% else %>
          <%= render 'bookmark_button', diary: diary %>
        <% end %>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= icon 'far', 'user' %>
            <%= diary.user.decorate.user_name %>
          </li>
          <li class="list-inline-item">
            <%= icon 'far', 'calendar' %>
            <%= l diary.created_at, format: :long %>
          </li>
        </ul>
        <p class="card-text"><%= diary.body %></p>
      </div>
    </div>
  </div>
</div>

Nikki/app/views/diaries/_form.html.erb
<%= form_with model: diary, local: false do |f| %>
  <%= render 'layouts/shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
    <div class="form-group">
    <%= f.label :diary_image %>
    <%= f.file_field :diary_image, class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :diary_image_cache %>
  </div>
  <div class='mt-3 mb-3'>
    <%= image_tag diary.diary_image.url,
                  id: 'preview',
                  size: '300x200' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

Nikki/app/views/diaries/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
    <div class="input-group-append">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

Nikki/app/views/diaries/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(diary_id: diary.id)),
          id: "js-bookmark-button-for-diary-#{diary.id}",
          class:"float-right",
          method: :delete,
          remote: true do %>
  <%= icon 'fas', 'star' %>
<% end %>

Nikki/app/views/diaries/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <%= render 'search_form', url: bookmarks_diaries_path %>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_diaries.present? %>
          <%= render @bookmark_diaries %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @bookmark_diaries %>
    </div>
  </div>
</div>

Nikki/app/views/diaries/edit.html.erb
<% content_for(:title, @diary.title) %>
<div class ="container">
  <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { diary: @diary } %>
    </div>
  </div>
</div>

Nikki/app/views/diaries/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <%= render 'search_form', url: diaries_path %>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @diaries.present? %>
          <%= render @diaries %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @diaries %>
    </div>
  </div>
</div>

Nikki/app/views/diaries/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { diary: @diary } %>
    </div>
  </div>
</div>

Nikki/app/views/diaries/show.html.erb
<% content_for(:title, @diary.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 日記内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag @diary.diary_image.url, class: 'card-img-top img-fluid', size: '300x200' %>
            </div>
            <div class='col-md-9'>
              <h3 class="d-inline"><%= @diary.title %></h3>
              <%= render 'crud_menus', diary: @diary if current_user.own?(@diary) %>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @diary.user.decorate.user_name %></li>
                <li class="list-inline-item"><%= l @diary.created_at, format: :long  %></li>
              </ul>
            </div>
          </div>
          <p><%= simple_format(@diary.body) %></p>
        </div>
      </article>
    </div>
  </div>

  <!-- コメントフォーム -->
  <%= render 'comments/form', { diary: @diary, comment: @comment } %>

  <!-- コメントエリア -->

  <%= render 'comments/comments', { comments: @comments } %>
</div>